// Copyright Buckley Builds LLC 2026 All Rights Reserved.

#include "PythonAPI/UEnvQueryService.h"

#if WITH_VIBEUE_EQS

#include "AIGraphNode.h"
#include "AIGraphTypes.h"
#include "Dom/JsonObject.h"
#include "EdGraph/EdGraphNode.h"
#include "EnvQueryServiceInternal.h"
#include "EnvironmentQuery/EnvQuery.h"
#include "EnvironmentQuery/EnvQueryGenerator.h"
#include "EnvironmentQuery/EnvQueryOption.h"
#include "EnvironmentQuery/EnvQueryTest.h"
#include "EnvironmentQuery/EnvQueryContext.h"
#include "EnvironmentQueryGraph.h"
#include "EnvironmentQueryGraphNode.h"
#include "EnvironmentQueryGraphNode_Option.h"
#include "EnvironmentQueryGraphNode_Test.h"
#include "Serialization/JsonSerializer.h"
#include "Serialization/JsonWriter.h"
#include "UObject/UnrealType.h"

namespace VibeEQS
{
	/**
	 * Gather every class under BaseClass through the cached helper (see GetClassHelper for what
	 * its Blueprint-priming call does — and, contrary to an earlier version of this comment,
	 * doesn't) and describe each one without ever calling FGraphNodeClassData::GetClass() —
	 * IsBlueprint() and GetPackageName() are both free flag/string reads set at construction, so
	 * listing performs no disk I/O.
	 */
	TArray<FEQSClassInfo> ListClasses(UClass* BaseClass)
	{
		TArray<FEQSClassInfo> Result;

		const TSharedPtr<FGraphNodeClassHelper> Helper = VibeEQS::GetClassHelper(BaseClass);
		if (!Helper.IsValid())
		{
			return Result;
		}

		TArray<FGraphNodeClassData> ClassData;
		Helper->GatherClasses(BaseClass, ClassData);

		Result.Reserve(ClassData.Num());
		for (FGraphNodeClassData& Data : ClassData)
		{
			FEQSClassInfo Info;
			Info.ClassName = Data.GetClassName();
			Info.Category = Data.GetCategory().ToString();
			Info.bIsBlueprint = Data.IsBlueprint();

			// GetPackageName() is empty for native classes (never populated by the constructor
			// TObjectIterator discovery uses) and the asset's package for Blueprint ones. Either
			// way this is a string built from already-known asset-registry/reflection data, not a
			// load.
			const FString PackageName = Data.GetPackageName();
			Info.ClassPath = PackageName.IsEmpty() ? Info.ClassName : PackageName + TEXT(".") + Info.ClassName;

			Result.Add(MoveTemp(Info));
		}
		return Result;
	}
}

TArray<FEQSClassInfo> UEnvQueryService::GetAvailableGeneratorTypes()
{
	return VibeEQS::ListClasses(UEnvQueryGenerator::StaticClass());
}

TArray<FEQSClassInfo> UEnvQueryService::GetAvailableTestTypes()
{
	return VibeEQS::ListClasses(UEnvQueryTest::StaticClass());
}

TArray<FEQSClassInfo> UEnvQueryService::GetAvailableContextTypes()
{
	return VibeEQS::ListClasses(UEnvQueryContext::StaticClass());
}

/**
 * GetQuery's serialisation. Named rather than anonymous: under a unity build an anonymous namespace
 * is shared with every other .cpp in the same blob, so same-named free helpers collide.
 */
namespace VibeEQSRead
{
	/**
	 * Every authorable property of Instance whose value differs from its class default.
	 *
	 * The CDO decides *whether* a property is reported and is deliberately not used to export it:
	 * an export against defaults is a delta, and the delta of a struct omits members left at their
	 * default — so a scoring value of (DefaultValue=0.0) would export as "()" and read back as
	 * something else entirely. VibeEQS::ExportPropertyValue passes Instance as its own delta
	 * container instead, which makes FProperty::ExportText_Direct take its `Data == Delta` branch and
	 * export the whole value. Both the filter and the export are the shared ones GetPropertyNames
	 * uses, so this map and that list can never disagree about a name or an encoding.
	 */
	TSharedRef<FJsonObject> CollectEditedProperties(const UObject* Instance)
	{
		const TSharedRef<FJsonObject> Properties = MakeShared<FJsonObject>();

		UClass* Class = Instance ? Instance->GetClass() : nullptr;
		const UObject* Defaults = Class ? Class->GetDefaultObject() : nullptr;
		if (!Defaults)
		{
			return Properties;
		}

		for (TFieldIterator<FProperty> It(Class); It; ++It)
		{
			const FProperty* Property = *It;
			if (!VibeEQS::IsAuthorableProperty(Property)
				|| Property->Identical_InContainer(Instance, Defaults))
			{
				continue;
			}

			Properties->SetStringField(Property->GetName(),
				VibeEQS::ExportPropertyValue(Property, Instance));
		}

		return Properties;
	}

	/**
	 * One option, with its tests.
	 *
	 * "properties" are the GENERATOR's, not the UEnvQueryOption's. That is not a shortcut: an option
	 * is a generator plus its tests, and UEnvQueryOption's own two UPROPERTYs (Generator, Tests) are
	 * structure this JSON already reports, carry no CPF_Edit, and are regenerated by the commit — so
	 * the option's own edited-property set is always empty and reporting it would tell a caller
	 * nothing about what it can tune.
	 *
	 * Tests come from the node's SubNodes, index-aligned with the "@test[n]" path segment, and
	 * include disabled ones. UEnvQueryOption::Tests would list only enabled tests
	 * (EnvironmentQueryGraph.cpp:90) and would therefore renumber every path after a disabled test —
	 * addressing a node the caller cannot see is the worse failure.
	 *
	 * Which is exactly why each test carries "enabled". bTestEnabled lives on the graph node
	 * (UEnvironmentQueryGraphNode_Test), not on the UEnvQueryTest instance, so no amount of property
	 * reflection over the instance could surface it: without this field a disabled test is
	 * indistinguishable from a live one here, while GetQueryInfo's TestCount — which sums the
	 * filtered UEnvQueryOption::Tests — reports a smaller number for the same asset with nothing
	 * explaining the difference. It is also the flag any round-trip (BuildQuery) has to carry to
	 * reproduce a query it just read.
	 */
	TSharedRef<FJsonObject> OptionToJson(const UEnvironmentQueryGraphNode_Option* OptionNode, int32 OptionIndex)
	{
		const TSharedRef<FJsonObject> Object = MakeShared<FJsonObject>();
		const FString OptionPath = VibeEQS::MakeOptionPath(OptionIndex);

		const UEnvQueryOption* OptionInstance = Cast<UEnvQueryOption>(ToRawPtr(OptionNode->NodeInstance));
		const UEnvQueryGenerator* Generator = OptionInstance ? ToRawPtr(OptionInstance->Generator) : nullptr;

		Object->SetStringField(TEXT("path"), OptionPath);
		Object->SetStringField(TEXT("guid"), OptionNode->NodeGuid.ToString());
		// Empty when the node carries no generator — a shape the commit would drop, so saying so is
		// the point rather than an omission.
		Object->SetStringField(TEXT("generator"),
			Generator ? Generator->GetClass()->GetName() : FString());
		Object->SetObjectField(TEXT("properties"), CollectEditedProperties(Generator));

		TArray<TSharedPtr<FJsonValue>> Tests;
		for (int32 TestIndex = 0; TestIndex < OptionNode->SubNodes.Num(); ++TestIndex)
		{
			const UAIGraphNode* TestNode = ToRawPtr(OptionNode->SubNodes[TestIndex]);
			if (!TestNode)
			{
				continue;
			}

			const UObject* TestInstance = ToRawPtr(TestNode->NodeInstance);
			const TSharedRef<FJsonObject> TestObject = MakeShared<FJsonObject>();
			TestObject->SetStringField(TEXT("path"),
				FString::Printf(TEXT("%s/@test[%d]"), *OptionPath, TestIndex));
			TestObject->SetStringField(TEXT("guid"), TestNode->NodeGuid.ToString());
			TestObject->SetStringField(TEXT("class"),
				TestInstance ? TestInstance->GetClass()->GetName() : FString());
			// A sub-node that is not a test node at all cannot be disabled — nothing filters it out
			// of anything — so it reports enabled rather than being described as switched off.
			const UEnvironmentQueryGraphNode_Test* AsTestNode =
				Cast<UEnvironmentQueryGraphNode_Test>(TestNode);
			TestObject->SetBoolField(TEXT("enabled"),
				AsTestNode ? AsTestNode->bTestEnabled != 0 : true);
			TestObject->SetObjectField(TEXT("properties"), CollectEditedProperties(TestInstance));
			Tests.Add(MakeShared<FJsonValueObject>(TestObject));
		}
		Object->SetArrayField(TEXT("tests"), Tests);

		return Object;
	}

	FString SerialiseJson(const TSharedRef<FJsonObject>& Object)
	{
		FString Out;
		const TSharedRef<TJsonWriter<>> Writer = TJsonWriterFactory<>::Create(&Out);
		FJsonSerializer::Serialize(Object, Writer);
		return Out;
	}

	/**
	 * A parseable failure. Callers walk "options" without checking anything else, so an error result
	 * carries an empty one rather than omitting the field and turning a handled failure into a
	 * crash in the caller.
	 */
	FString QueryError(const FString& Message)
	{
		const TSharedRef<FJsonObject> Object = MakeShared<FJsonObject>();
		Object->SetStringField(TEXT("error"), Message);
		Object->SetArrayField(TEXT("options"), TArray<TSharedPtr<FJsonValue>>());
		return SerialiseJson(Object);
	}

	/**
	 * Load AssetPath and hand back its existing graph, or refuse. Empty on success.
	 *
	 * The read counterpart of VibeEQS::OpenWriteGuard, and pointedly NOT that function: OpenWriteGuard
	 * runs EnsureGraph, which creates the graph, spawns nodes and regenerates the option list — so a
	 * read routed through it would rewrite every asset it was asked to look at. An asset with no graph
	 * is reported as such instead.
	 */
	FString OpenReadGraph(const FString& AssetPath, UEnvironmentQueryGraph*& OutGraph)
	{
		OutGraph = nullptr;

		if (AssetPath.IsEmpty())
		{
			return TEXT("AssetPath is empty");
		}

		// Length only, not CheckWritableAssetPath: READING an engine-content query is legitimate,
		// but the object-path lookup below still builds an FName per segment.
		const FString LengthError = VibeEQS::CheckNameLength(AssetPath, TEXT("AssetPath"));
		if (!LengthError.IsEmpty())
		{
			return LengthError;
		}

		UEnvQuery* Query = LoadObject<UEnvQuery>(nullptr, *AssetPath, nullptr, LOAD_NoWarn | LOAD_Quiet);
		if (!Query)
		{
			return FString::Printf(TEXT("Environment Query not found: %s"), *AssetPath);
		}

		UEnvironmentQueryGraph* Graph = Cast<UEnvironmentQueryGraph>(Query->EdGraph);
		if (!Graph)
		{
			return FString::Printf(
				TEXT("%s has no editor graph. It has never been opened in the Environment Query "
					 "editor, and reading is not allowed to create one. Run CompileAndSave to build "
					 "it."),
				*AssetPath);
		}

		if (!VibeEQS::FindRootNode(Graph))
		{
			return FString::Printf(TEXT("%s has no root node in its editor graph"), *AssetPath);
		}

		OutGraph = Graph;
		return FString();
	}
}

FString UEnvQueryService::GetQuery(const FString& AssetPath)
{
	UEnvironmentQueryGraph* Graph = nullptr;
	const FString OpenError = VibeEQSRead::OpenReadGraph(AssetPath, Graph);
	if (!OpenError.IsEmpty())
	{
		return VibeEQSRead::QueryError(OpenError);
	}

	const TArray<UEnvironmentQueryGraphNode_Option*> OptionNodes = VibeEQS::GetOptionNodes(Graph);

	TArray<TSharedPtr<FJsonValue>> Options;
	Options.Reserve(OptionNodes.Num());
	for (int32 Index = 0; Index < OptionNodes.Num(); ++Index)
	{
		Options.Add(MakeShared<FJsonValueObject>(VibeEQSRead::OptionToJson(OptionNodes[Index], Index)));
	}

	const TSharedRef<FJsonObject> Object = MakeShared<FJsonObject>();
	Object->SetArrayField(TEXT("options"), Options);
	return VibeEQSRead::SerialiseJson(Object);
}

TArray<FEQSPropertyInfo> UEnvQueryService::GetPropertyNames(const FString& AssetPath,
	const FString& NodePath)
{
	TArray<FEQSPropertyInfo> Result;

	UEnvironmentQueryGraph* Graph = nullptr;
	if (!VibeEQSRead::OpenReadGraph(AssetPath, Graph).IsEmpty())
	{
		return Result;
	}

	FString ResolveError;
	const UObject* Instance = VibeEQS::ResolvePropertyTarget(Graph, NodePath, AssetPath, ResolveError);
	if (!Instance)
	{
		return Result;
	}

	for (TFieldIterator<FProperty> It(Instance->GetClass()); It; ++It)
	{
		const FProperty* Property = *It;
		if (!VibeEQS::IsAuthorableProperty(Property))
		{
			continue;
		}

		FEQSPropertyInfo Info;
		Info.Name = Property->GetName();
		Info.Type = Property->GetCPPType();
		Info.Value = VibeEQS::ExportPropertyValue(Property, Instance);
		Info.bIsDataProvider = VibeEQS::IsDataProviderProperty(Property);
		Result.Add(MoveTemp(Info));
	}

	return Result;
}

FString UEnvQueryService::GetPropertyValue(const FString& AssetPath, const FString& NodePath,
	const FString& PropertyName)
{
	UEnvironmentQueryGraph* Graph = nullptr;
	const FString OpenError = VibeEQSRead::OpenReadGraph(AssetPath, Graph);
	if (!OpenError.IsEmpty())
	{
		return FString::Printf(TEXT("ERROR: %s"), *OpenError);
	}

	FString ResolveError;
	const UObject* Instance = VibeEQS::ResolvePropertyTarget(Graph, NodePath, AssetPath, ResolveError);
	if (!Instance)
	{
		return FString::Printf(TEXT("ERROR: %s"), *ResolveError);
	}

	const FString NameError = VibeEQS::CheckNameLength(PropertyName, TEXT("PropertyName"));
	if (!NameError.IsEmpty())
	{
		return FString::Printf(TEXT("ERROR: %s"), *NameError);
	}

	const FProperty* Property = Instance->GetClass()->FindPropertyByName(FName(*PropertyName));
	if (!VibeEQS::IsAuthorableProperty(Property))
	{
		// One message for "no such property" and for "present but not authorable", because the
		// remedy is the same and the distinction the caller actually needs — what CAN be read — is
		// the list GetPropertyNames returns.
		return FString::Printf(
			TEXT("ERROR: %s has no authorable property named '%s'. Call GetPropertyNames for the "
				 "names this accepts."),
			*Instance->GetClass()->GetName(), *PropertyName);
	}

	return VibeEQS::ExportPropertyValue(Property, Instance);
}

namespace VibeEQSRead
{
	/**
	 * The one-line form of the sparse-graph diagnostic, so the wording cannot drift between the two
	 * shapes that produce it (no graph at all, and a graph whose root feeds nothing).
	 */
	FString SparseGraphIssue(const FString& AssetPath, int32 OptionCount, const TCHAR* Detail)
	{
		return FString::Printf(
			TEXT("sparse graph: %s has %d option(s) but %s, so nothing here is addressable and "
				 "GetQuery reports an empty query. Run RepairGraphFromOptions to rebuild the option "
				 "and test nodes from UEnvQuery::Options."),
			*AssetPath, OptionCount, Detail);
	}

	/**
	 * Every TSubclassOf<UEnvQueryContext> reachable from Container that is None while the class
	 * default supplies one.
	 *
	 * "While the class default supplies one" is the whole discrimination and is not a hedge. A null
	 * context is NOT a defect by itself: UEnvQueryGenerator_ProjectedPoints::NavDataOverrideContext
	 * and the second half of an FEnvDirection are legitimately empty on a healthy query, so a bare
	 * null test would fire on almost every asset and the "healthy query returns nothing" contract
	 * would be dead on arrival. A context the constructor populated and the asset holds as None is a
	 * different thing: someone (or a failed class load) cleared a value the class considers required.
	 *
	 * The honest limit: once a referenced context class fails to load, the property reads as null and
	 * is indistinguishable in memory from one cleared on purpose. Both are reported, with the same
	 * remedy, and neither can be told from the other without the package linker.
	 *
	 * Recurses into struct members, because FEnvDirection — three context references, used by
	 * UEnvQueryTest_Dot and UEnvQueryTest_Trace — is where a good third of EQS's context references
	 * live. Recursion terminates because a USTRUCT cannot contain itself by value.
	 */
	void CollectUnresolvedContexts(const UStruct* Struct, const void* Container, const void* Defaults,
		const FString& NodePath, const FString& OwnerClassName, const FString& PropertyPrefix,
		TArray<FString>& OutIssues)
	{
		if (!Struct || !Container || !Defaults)
		{
			return;
		}

		for (TFieldIterator<FProperty> It(Struct); It; ++It)
		{
			const FProperty* Property = *It;
			if (!VibeEQS::IsAuthorableProperty(Property))
			{
				continue;
			}

			const FString QualifiedName = PropertyPrefix + Property->GetName();

			if (const FClassProperty* ClassProperty = CastField<const FClassProperty>(Property))
			{
				if (!ClassProperty->MetaClass
					|| !ClassProperty->MetaClass->IsChildOf(UEnvQueryContext::StaticClass()))
				{
					continue;
				}

				const UObject* Value = ClassProperty->GetObjectPropertyValue(
					ClassProperty->ContainerPtrToValuePtr<void>(Container));
				const UObject* DefaultValue = ClassProperty->GetObjectPropertyValue(
					ClassProperty->ContainerPtrToValuePtr<void>(Defaults));

				if (Value == nullptr && DefaultValue != nullptr)
				{
					OutIssues.Add(FString::Printf(
						TEXT("%s: unresolved context — '%s' on %s is None, while the class default is "
							 "%s. A null UEnvQueryContext makes the query produce nothing for this "
							 "node; either it was cleared by hand or the class it referenced no longer "
							 "loads. Set it with SetPropertyValue."),
						*NodePath, *QualifiedName, *OwnerClassName, *DefaultValue->GetName()));
				}
				continue;
			}

			if (const FStructProperty* StructProperty = CastField<const FStructProperty>(Property))
			{
				CollectUnresolvedContexts(StructProperty->Struct,
					StructProperty->ContainerPtrToValuePtr<void>(Container),
					StructProperty->ContainerPtrToValuePtr<void>(Defaults),
					NodePath, OwnerClassName, QualifiedName + TEXT("."), OutIssues);
			}
		}
	}

	/** CollectUnresolvedContexts against an object and its own CDO. */
	void CollectUnresolvedContextsOn(const UObject* Instance, const FString& NodePath,
		TArray<FString>& OutIssues)
	{
		UClass* Class = Instance ? Instance->GetClass() : nullptr;
		const UObject* Defaults = Class ? Class->GetDefaultObject() : nullptr;
		if (!Defaults)
		{
			return;
		}
		CollectUnresolvedContexts(Class, Instance, Defaults, NodePath, Class->GetName(), FString(),
			OutIssues);
	}

	/**
	 * Diagnose one node and its sub-nodes.
	 *
	 * Visited is a cycle guard, not an optimisation. The malformed graphs this function exists to
	 * diagnose are exactly the ones that can hold a SubNodes entry pointing back at an ancestor —
	 * nothing in UAIGraphNode forbids it — and a validator that hangs on the shape it was written to
	 * report is worse than no validator at all.
	 */
	void ValidateNode(const UEnvironmentQueryGraphNode* Node, const FString& NodePath,
		TSet<const UEdGraphNode*>& Visited, TArray<FString>& OutIssues)
	{
		if (!Node || Visited.Contains(Node))
		{
			return;
		}
		Visited.Add(Node);

		// UAIGraphNode::HasErrors() is ErrorMessage.Len() > 0 || NodeInstance == nullptr
		// (AIGraphNode.cpp:409-412). Gated on the engine's own predicate, then split by cause,
		// because the two need different remedies and reporting both for one defect is noise.
		if (Node->HasErrors())
		{
			if (Node->NodeInstance == nullptr)
			{
				OutIssues.Add(FString::Printf(
					TEXT("%s: node class failed to load — the node carries no instance (class data: "
						 "'%s'). The class was renamed, deleted, or lives in a module that is not "
						 "loaded; the next commit drops this node."),
					*NodePath, *Node->ClassData.GetClassName()));
			}
			else
			{
				OutIssues.Add(FString::Printf(TEXT("%s: node class failed to load — %s"),
					*NodePath, *Node->ErrorMessage));
			}
		}

		if (const UEnvironmentQueryGraphNode_Option* OptionNode =
			Cast<UEnvironmentQueryGraphNode_Option>(Node))
		{
			const UEnvQueryOption* OptionInstance =
				Cast<UEnvQueryOption>(ToRawPtr(OptionNode->NodeInstance));
			const UEnvQueryGenerator* Generator =
				OptionInstance ? ToRawPtr(OptionInstance->Generator) : nullptr;

			// Only when the option object exists: a node with no instance at all already reported
			// above, and saying "no generator" about it too would describe one defect twice.
			if (OptionInstance && !Generator)
			{
				OutIssues.Add(FString::Printf(
					TEXT("%s: no generator — an option IS its generator, and "
						 "UEnvironmentQueryGraph::UpdateAsset keeps only option nodes that carry one "
						 "(EnvironmentQueryGraph.cpp:75), so the next commit drops this option and "
						 "every test on it. Give it one with SetOptionGenerator."),
					*NodePath));
			}

			CollectUnresolvedContextsOn(Generator, NodePath, OutIssues);
		}
		else
		{
			CollectUnresolvedContextsOn(ToRawPtr(Node->NodeInstance), NodePath, OutIssues);
		}

		for (int32 SubIndex = 0; SubIndex < Node->SubNodes.Num(); ++SubIndex)
		{
			const FString SubPath = FString::Printf(TEXT("%s/@test[%d]"), *NodePath, SubIndex);
			const UEnvironmentQueryGraphNode* SubNode =
				Cast<UEnvironmentQueryGraphNode>(ToRawPtr(Node->SubNodes[SubIndex]));
			if (!SubNode)
			{
				OutIssues.Add(FString::Printf(
					TEXT("%s: sub-node is null or not an Environment Query node, so nothing can "
						 "address it and the next commit drops it."),
					*SubPath));
				continue;
			}
			ValidateNode(SubNode, SubPath, Visited, OutIssues);
		}
	}
}

TArray<FString> UEnvQueryService::ValidateQuery(const FString& AssetPath)
{
	TArray<FString> Issues;

	if (AssetPath.IsEmpty())
	{
		Issues.Add(TEXT("AssetPath is empty"));
		return Issues;
	}

	// LoadObject, exactly as GetQuery and GetQueryInfo do — never VibeEQS::OpenWriteGuard. That path
	// runs EnsureGraph -> UEnvironmentQueryGraph::Initialize() -> SpawnMissingNodes(), which REPAIRS
	// the sparse graph reported below. Routing a validator through it would silently heal every
	// asset it looked at, report the healed state, and turn a read into a write.
	const UEnvQuery* Query =
		LoadObject<UEnvQuery>(nullptr, *AssetPath, nullptr, LOAD_NoWarn | LOAD_Quiet);
	if (!Query)
	{
		Issues.Add(FString::Printf(TEXT("Environment Query not found: %s"), *AssetPath));
		return Issues;
	}

	const int32 OptionCount = Query->GetOptions().Num();
	UEnvironmentQueryGraph* Graph = Cast<UEnvironmentQueryGraph>(Query->EdGraph);

	if (!Graph)
	{
		// No graph and no options is a query that has simply never been opened — a fact GetQueryInfo
		// reports (bHasGraph) and not a defect. No graph WITH options is the sparse shape in its
		// most complete form: the options exist and nothing in the editor can reach them.
		if (OptionCount > 0)
		{
			Issues.Add(VibeEQSRead::SparseGraphIssue(AssetPath, OptionCount,
				TEXT("no editor graph at all")));
		}
		return Issues;
	}

	if (!VibeEQS::FindRootNode(Graph))
	{
		Issues.Add(FString::Printf(
			TEXT("no root node: %s has an editor graph with no UEnvironmentQueryGraphNode_Root, so "
				 "no option can be linked into the query and every commit would rebuild an empty "
				 "option list."),
			*AssetPath));
		return Issues;
	}

	const TArray<UEnvironmentQueryGraphNode_Option*> OptionNodes = VibeEQS::GetOptionNodes(Graph);
	if (OptionCount > 0 && OptionNodes.Num() == 0)
	{
		Issues.Add(VibeEQSRead::SparseGraphIssue(AssetPath, OptionCount,
			TEXT("its graph's root feeds no option node")));
	}
	// The PARTIAL form of the same illness, and the one that would otherwise validate clean while
	// every mutator refused — the BT_Villager anti-pattern this call exists to prevent. Some options
	// linked, some not: the sparse test above sees a non-zero count and says nothing, the linked
	// nodes walk clean, and the caller is told the query is healthy. The next write then runs
	// EnsureGraph -> Initialize -> SpawnMissingNodes -> UpdateAsset, rebuilds a SHORTER option list,
	// and is refused — permanently, because EnsureGraph marks the damaged in-memory copy.
	//
	// Skipped entirely when nothing is linked: that is the total case, already reported once above,
	// and repeating it per option would bury the one line that matters.
	else if (OptionNodes.Num() > 0)
	{
		TSet<const UObject*> LinkedInstances;
		for (const UEnvironmentQueryGraphNode_Option* Node : OptionNodes)
		{
			if (Node && Node->NodeInstance)
			{
				LinkedInstances.Add(ToRawPtr(Node->NodeInstance));
			}
		}

		const TArray<UEnvQueryOption*>& Options = Query->GetOptions();
		int32 CarriedCount = 0;
		for (const UEnvQueryOption* Option : Options)
		{
			CarriedCount += (Option && LinkedInstances.Contains(Option)) ? 1 : 0;
		}

		for (int32 Index = 0; Index < Options.Num(); ++Index)
		{
			const UEnvQueryOption* Option = Options[Index];
			if (Option && LinkedInstances.Contains(Option))
			{
				continue;
			}

			const UEnvQueryGenerator* Generator = Option ? ToRawPtr(Option->Generator) : nullptr;
			Issues.Add(FString::Printf(
				TEXT("orphaned option: UEnvQuery::Options[%d] (%s) is not carried by any root-linked "
					 "option node, so only %d of this query's %d options are still reachable. "
					 "UEnvironmentQueryGraph::UpdateAsset regenerates the list from root-linked nodes "
					 "alone, so the next write drops this option — and because EnsureGraph sees the "
					 "drop while merely opening the asset, that write is refused and this in-memory "
					 "copy is marked un-writable until it is genuinely reloaded. "
					 "RepairGraphFromOptions cannot fix it: SpawnMissingNodes skips any option that "
					 "already has a node anywhere in Graph->Nodes "
					 "(EnvironmentQueryGraph.cpp:381-413), so a node left in the graph but unlinked "
					 "from the root is never relinked. Relink or delete the stray node in the "
					 "Environment Query editor."),
				Index,
				Generator ? *Generator->GetClass()->GetName()
						  : (Option ? TEXT("no generator") : TEXT("null option")),
				CarriedCount, OptionCount));
		}
	}

	TSet<const UEdGraphNode*> Visited;
	for (int32 Index = 0; Index < OptionNodes.Num(); ++Index)
	{
		VibeEQSRead::ValidateNode(OptionNodes[Index], VibeEQS::MakeOptionPath(Index), Visited, Issues);
	}

	return Issues;
}

#else // WITH_VIBEUE_EQS

TArray<FEQSClassInfo> UEnvQueryService::GetAvailableGeneratorTypes()
{
	return TArray<FEQSClassInfo>();
}

TArray<FEQSClassInfo> UEnvQueryService::GetAvailableTestTypes()
{
	return TArray<FEQSClassInfo>();
}

TArray<FEQSClassInfo> UEnvQueryService::GetAvailableContextTypes()
{
	return TArray<FEQSClassInfo>();
}

FString UEnvQueryService::GetQuery(const FString&)
{
	// Shaped like a real result — "options" present and empty — so a caller that walks the array
	// without checking "error" gets an empty query rather than a crash.
	return TEXT("{\"error\":\"EQS authoring is unavailable: the EnvironmentQueryEditor plugin is not "
				"enabled in this build (WITH_VIBEUE_EQS=0).\",\"options\":[]}");
}

TArray<FEQSPropertyInfo> UEnvQueryService::GetPropertyNames(const FString&, const FString&)
{
	return TArray<FEQSPropertyInfo>();
}

FString UEnvQueryService::GetPropertyValue(const FString&, const FString&, const FString&)
{
	return TEXT("ERROR: EQS authoring is unavailable: the EnvironmentQueryEditor plugin is not "
				"enabled in this build (WITH_VIBEUE_EQS=0).");
}

TArray<FString> UEnvQueryService::ValidateQuery(const FString&)
{
	// A non-empty array, not an empty one: an empty result means "healthy", and reporting a query
	// this build cannot even read as healthy is the one answer that would be a lie.
	return TArray<FString>{
		TEXT("EQS authoring is unavailable: the EnvironmentQueryEditor plugin is not enabled in this "
			 "build (WITH_VIBEUE_EQS=0).") };
}

#endif // WITH_VIBEUE_EQS
